WITH CAR AS (SELECT *
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
HAVING COUNT(CAR_ID) >= 5
           )

SELECT DATE_FORMAT(START_DATE, '%m') MONTH,
        CAR_ID,
        COUNT(HISTORY_ID) RECORDS
FROM CAR
WHERE CAR_ID IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 GROUP BY CAR_ID
                 HAVING COUNT(CAR_ID) >= 5) 
GROUP BY DATE_FORMAT(START_DATE, '%m'), CAR_ID
ORDER BY MONTH, CAR_ID DESC
