-- 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회


-- 내 풀이
SELECT 
    PRODUCT_ID, PRODUCT_NAME,
    SUM(TOTAL_SALES) AS TOTAL_SALES
FROM(
    SELECT 
        P.PRODUCT_ID,
        P.PRODUCT_NAME, 
        P.PRICE*O.AMOUNT AS TOTAL_SALES
    FROM FOOD_PRODUCT P, FOOD_ORDER O
    WHERE P.PRODUCT_ID = O.PRODUCT_ID
    AND TO_CHAR(O.PRODUCE_DATE, 'YYYY-MM') = '2022-05')
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID


  
-- 다른 풀이
SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME, 
    SUM(P.PRICE*O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P, FOOD_ORDER O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
AND TO_CHAR(O.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID


-- 인라인 뷰를 사용하지 않아도 바로 풀 수 있다.
-- 문제 풀이: https://school.programmers.co.kr/learn/courses/30/lessons/131117?language=oracle
