
--  내 풀이 (오답)
SELECT 
    TO_CHAR(O.SALES_DATE, 'YYYY') AS YEAR, 
    TO_CHAR(O.SALES_DATE, 'MM') AS MONTH, 
    U.GENDER,
    COUNT(U.USER_ID) AS USERS
FROM ONLINE_SALE O, USER_INFO U
WHERE O.USER_ID = U.USER_ID
AND U.GENDER IS NOT NULL
GROUP BY TO_CHAR(O.SALES_DATE, 'YYYY'), TO_CHAR(O.SALES_DATE, 'MM'), U.GENDER
ORDER BY YEAR, MONTH, U.GENDER



-- 정답
-- TO_CHAR를 TO_NUMBER로 한번 더 감싸서 출력 포맷을 바꿔야 한다.
-- DISTINCT를 사용하여 USER_ID의 중복을 없애야 한다.
SELECT
     TO_NUMBER(TO_CHAR(O.SALES_DATE, 'YYYY')) AS YEAR, 
    TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM')) AS MONTH, 
    U.GENDER,
    COUNT(DISTINCT U.USER_ID) AS USERS
FROM ONLINE_SALE O, USER_INFO U
WHERE O.USER_ID = U.USER_ID
AND U.GENDER IS NOT NULL
GROUP BY TO_CHAR(O.SALES_DATE, 'YYYY'), TO_CHAR(O.SALES_DATE, 'MM'), U.GENDER
ORDER BY YEAR, MONTH, U.GENDER



-- 다른 풀이
-- EXTRACT 사용해서 연, 월만 추출
-- DISTINCT로 중복 제거하기 -> 회원의 수를 집계한느 것이기 때문에 여러 번 구매한 회원은 중복 제거해야하는 듯?
SELECT 
    EXTRACT(YEAR FROM O.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM O.SALES_DATE) AS MONTH,
    U.GENDER, COUNT(DISTINCT O.USER_ID) AS USERS
FROM USER_INFO U, ONLINE_SALE O
WHERE U.USER_ID = O.USER_ID
AND U.GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM O.SALES_DATE), 
         EXTRACT(MONTH FROM O.SALES_DATE),
         U.GENDER
ORDER BY YEAR, MONTH, GENDER



-- 문제 출처: https://school.programmers.co.kr/learn/courses/30/lessons/131532


