-- WHERE절에서 H.START_DATE > '2022-11-30' OR H.END_DATE < '2022-11-01' 쓰면 CAR_TYPE이 필터링이 안 되고, 이상하게 조인이 될까?

SELECT CAR_ID, CAR_TYPE, FEE
FROM(
    SELECT 
        C.CAR_ID, H.END_DATE - H.START_DATE + 1 AS DUR,
        C.CAR_TYPE,
        CASE 
        WHEN CAR_TYPE = '세단' THEN (H.END_DATE - H.START_DATE + 1)*C.DAILY_FEE*0.9
        WHEN CAR_TYPE = 'SUV' THEN (H.END_DATE - H.START_DATE + 1)*C.DAILY_FEE*0.92
        END AS FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H, CAR_RENTAL_COMPANY_CAR C
    WHERE H.CAR_ID = C.CAR_ID
    AND C.CAR_TYPE IN ('세단', 'SUV')
    AND (TO_CHAR(H.START_DATE, 'YYYY-MM-DD') > '2022-11-30' 
         OR TO_CHAR(H.END_DATE, 'YYYY-MM-DD') < '2022-11-01')
    AND (H.END_DATE - H.START_DATE >= 30 AND H.END_DATE - H.START_DATE < 90)
    )
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC

-- 문제 출처: https://school.programmers.co.kr/learn/courses/30/lessons/157339?language=oracle
